required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/rakyll/statik",
]

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/grpc-gateway"

[[constraint]]
  name = "github.com/rakyll/statik"
  version = "0.1.5"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    non-go = false
    unused-packages = false
